//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Velixo.Reports.AcumaticaSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.acumatica.com/untyped/", ConfigurationName="AcumaticaSoap.ScreenSoap")]
    public interface ScreenSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Clear", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Clear(string screenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Clear", ReplyAction="*")]
        System.Threading.Tasks.Task ClearAsync(string screenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/GetProcessStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        Velixo.Reports.AcumaticaSoap.ProcessResult GetProcessStatus(string screenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/GetProcessStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Velixo.Reports.AcumaticaSoap.ProcessResult> GetProcessStatusAsync(string screenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/GetScenario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        Velixo.Reports.AcumaticaSoap.Command[] GetScenario(string scenario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/GetScenario", ReplyAction="*")]
        System.Threading.Tasks.Task<Velixo.Reports.AcumaticaSoap.Command[]> GetScenarioAsync(string scenario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/GetSchema", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        Velixo.Reports.AcumaticaSoap.Content GetSchema(string screenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/GetSchema", ReplyAction="*")]
        System.Threading.Tasks.Task<Velixo.Reports.AcumaticaSoap.Content> GetSchemaAsync(string screenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/SetSchema", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        void SetSchema(string screenID, Velixo.Reports.AcumaticaSoap.Content schema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/SetSchema", ReplyAction="*")]
        System.Threading.Tasks.Task SetSchemaAsync(string screenID, Velixo.Reports.AcumaticaSoap.Content schema);
        
        // CODEGEN: Parameter 'ExportResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Export", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        Velixo.Reports.AcumaticaSoap.ExportResponse Export(Velixo.Reports.AcumaticaSoap.ExportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Export", ReplyAction="*")]
        System.Threading.Tasks.Task<Velixo.Reports.AcumaticaSoap.ExportResponse> ExportAsync(Velixo.Reports.AcumaticaSoap.ExportRequest request);
        
        // CODEGEN: Parameter 'data' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Import", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        Velixo.Reports.AcumaticaSoap.ImportResponse Import(Velixo.Reports.AcumaticaSoap.ImportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Import", ReplyAction="*")]
        System.Threading.Tasks.Task<Velixo.Reports.AcumaticaSoap.ImportResponse> ImportAsync(Velixo.Reports.AcumaticaSoap.ImportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Submit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        Velixo.Reports.AcumaticaSoap.Content[] Submit(string screenID, Velixo.Reports.AcumaticaSoap.Command[] commands);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Submit", ReplyAction="*")]
        System.Threading.Tasks.Task<Velixo.Reports.AcumaticaSoap.Content[]> SubmitAsync(string screenID, Velixo.Reports.AcumaticaSoap.Command[] commands);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        Velixo.Reports.AcumaticaSoap.LoginResult Login(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<Velixo.Reports.AcumaticaSoap.LoginResult> LoginAsync(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        void Logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task LogoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/SetBusinessDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        void SetBusinessDate(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/SetBusinessDate", ReplyAction="*")]
        System.Threading.Tasks.Task SetBusinessDateAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/SetLocaleName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        void SetLocaleName(string localeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/SetLocaleName", ReplyAction="*")]
        System.Threading.Tasks.Task SetLocaleNameAsync(string localeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/SetSchemaMode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        void SetSchemaMode(Velixo.Reports.AcumaticaSoap.SchemaMode mode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/SetSchemaMode", ReplyAction="*")]
        System.Threading.Tasks.Task SetSchemaModeAsync(Velixo.Reports.AcumaticaSoap.SchemaMode mode);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class ProcessResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ProcessStatus statusField;
        
        private int secondsField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ProcessStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Seconds {
            get {
                return this.secondsField;
            }
            set {
                this.secondsField = value;
                this.RaisePropertyChanged("Seconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public enum ProcessStatus {
        
        /// <remarks/>
        NotExists,
        
        /// <remarks/>
        InProcess,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        Aborted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class LoginResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ErrorCode codeField;
        
        private string messageField;
        
        private string sessionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ErrorCode Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
                this.RaisePropertyChanged("Session");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public enum ErrorCode {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        INVALID_CREDENTIALS,
        
        /// <remarks/>
        INTERNAL_ERROR,
        
        /// <remarks/>
        INVALID_API_VERSION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class ImportResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool processedField;
        
        private string errorField;
        
        private Value[] keysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Processed {
            get {
                return this.processedField;
            }
            set {
                this.processedField = value;
                this.RaisePropertyChanged("Processed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Value[] Keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
                this.RaisePropertyChanged("Keys");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Value : Field {
        
        private string messageField;
        
        private bool isErrorField;
        
        private string errorLevelField;
        
        public Value() {
            this.isErrorField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
                this.RaisePropertyChanged("IsError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorLevel {
            get {
                return this.errorLevelField;
            }
            set {
                this.errorLevelField = value;
                this.RaisePropertyChanged("ErrorLevel");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Attachment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Value))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Field : Command {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Action))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Key))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Parameter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewRow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeleteRow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RowNumber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Answer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EveryValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Field))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Attachment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Value))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Command : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldNameField;
        
        private string objectNameField;
        
        private string valueField;
        
        private bool commitField;
        
        private bool ignoreErrorField;
        
        private Command linkedCommandField;
        
        private string nameField;
        
        private ElementDescriptor descriptorField;
        
        public Command() {
            this.commitField = false;
            this.ignoreErrorField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
                this.RaisePropertyChanged("FieldName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("ObjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Commit {
            get {
                return this.commitField;
            }
            set {
                this.commitField = value;
                this.RaisePropertyChanged("Commit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IgnoreError {
            get {
                return this.ignoreErrorField;
            }
            set {
                this.ignoreErrorField = value;
                this.RaisePropertyChanged("IgnoreError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Command LinkedCommand {
            get {
                return this.linkedCommandField;
            }
            set {
                this.linkedCommandField = value;
                this.RaisePropertyChanged("LinkedCommand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public ElementDescriptor Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
                this.RaisePropertyChanged("Descriptor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class ElementDescriptor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string displayNameField;
        
        private bool isDisabledField;
        
        private bool isRequiredField;
        
        private ElementTypes elementTypeField;
        
        private int lengthLimitField;
        
        private string inputMaskField;
        
        private string displayRulesField;
        
        private string[] allowedValuesField;
        
        private Container containerField;
        
        private string actionIconField;
        
        private int fieldPriorityField;
        
        private PXSpecialButtonType buttonTypeField;
        
        private string linkCommandField;
        
        private bool visibleField;
        
        private bool isTimeListField;
        
        private System.Nullable<bool> preserveTimeField;
        
        private string dependsOnField;
        
        private string stateColumnField;
        
        public ElementDescriptor() {
            this.isDisabledField = false;
            this.isRequiredField = false;
            this.elementTypeField = ElementTypes.String;
            this.lengthLimitField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
                this.RaisePropertyChanged("DisplayName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsDisabled {
            get {
                return this.isDisabledField;
            }
            set {
                this.isDisabledField = value;
                this.RaisePropertyChanged("IsDisabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsRequired {
            get {
                return this.isRequiredField;
            }
            set {
                this.isRequiredField = value;
                this.RaisePropertyChanged("IsRequired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(ElementTypes.String)]
        public ElementTypes ElementType {
            get {
                return this.elementTypeField;
            }
            set {
                this.elementTypeField = value;
                this.RaisePropertyChanged("ElementType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int LengthLimit {
            get {
                return this.lengthLimitField;
            }
            set {
                this.lengthLimitField = value;
                this.RaisePropertyChanged("LengthLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string InputMask {
            get {
                return this.inputMaskField;
            }
            set {
                this.inputMaskField = value;
                this.RaisePropertyChanged("InputMask");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DisplayRules {
            get {
                return this.displayRulesField;
            }
            set {
                this.displayRulesField = value;
                this.RaisePropertyChanged("DisplayRules");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public string[] AllowedValues {
            get {
                return this.allowedValuesField;
            }
            set {
                this.allowedValuesField = value;
                this.RaisePropertyChanged("AllowedValues");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Container Container {
            get {
                return this.containerField;
            }
            set {
                this.containerField = value;
                this.RaisePropertyChanged("Container");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ActionIcon {
            get {
                return this.actionIconField;
            }
            set {
                this.actionIconField = value;
                this.RaisePropertyChanged("ActionIcon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int FieldPriority {
            get {
                return this.fieldPriorityField;
            }
            set {
                this.fieldPriorityField = value;
                this.RaisePropertyChanged("FieldPriority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public PXSpecialButtonType ButtonType {
            get {
                return this.buttonTypeField;
            }
            set {
                this.buttonTypeField = value;
                this.RaisePropertyChanged("ButtonType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string LinkCommand {
            get {
                return this.linkCommandField;
            }
            set {
                this.linkCommandField = value;
                this.RaisePropertyChanged("LinkCommand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool Visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
                this.RaisePropertyChanged("Visible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool IsTimeList {
            get {
                return this.isTimeListField;
            }
            set {
                this.isTimeListField = value;
                this.RaisePropertyChanged("IsTimeList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<bool> PreserveTime {
            get {
                return this.preserveTimeField;
            }
            set {
                this.preserveTimeField = value;
                this.RaisePropertyChanged("PreserveTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string DependsOn {
            get {
                return this.dependsOnField;
            }
            set {
                this.dependsOnField = value;
                this.RaisePropertyChanged("DependsOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string StateColumn {
            get {
                return this.stateColumnField;
            }
            set {
                this.stateColumnField = value;
                this.RaisePropertyChanged("StateColumn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public enum ElementTypes {
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        AsciiString,
        
        /// <remarks/>
        StringSelector,
        
        /// <remarks/>
        ExplicitSelector,
        
        /// <remarks/>
        Number,
        
        /// <remarks/>
        Option,
        
        /// <remarks/>
        WideOption,
        
        /// <remarks/>
        Calendar,
        
        /// <remarks/>
        Action,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Container : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Field[] fieldsField;
        
        private string nameField;
        
        private Command[] serviceCommandsField;
        
        private Container[] childrenField;
        
        private string displayNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Field[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("Fields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Command[] ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
                this.RaisePropertyChanged("ServiceCommands");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public Container[] Children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
                this.RaisePropertyChanged("Children");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
                this.RaisePropertyChanged("DisplayName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public enum PXSpecialButtonType {
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        Save,
        
        /// <remarks/>
        SaveNotClose,
        
        /// <remarks/>
        Cancel,
        
        /// <remarks/>
        Refresh,
        
        /// <remarks/>
        Report,
        
        /// <remarks/>
        First,
        
        /// <remarks/>
        Next,
        
        /// <remarks/>
        Prev,
        
        /// <remarks/>
        Last,
        
        /// <remarks/>
        Insert,
        
        /// <remarks/>
        Delete,
        
        /// <remarks/>
        Approve,
        
        /// <remarks/>
        ApproveAll,
        
        /// <remarks/>
        Process,
        
        /// <remarks/>
        ProcessAll,
        
        /// <remarks/>
        EditDetail,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Action : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Key : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Parameter : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class NewRow : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class DeleteRow : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class RowNumber : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Answer : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class EveryValue : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Attachment : Field {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Field fieldField;
        
        private FilterCondition conditionField;
        
        private object valueField;
        
        private object value2Field;
        
        private int openBracketsField;
        
        private int closeBracketsField;
        
        private FilterOperator operatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Field Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FilterCondition Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
                this.RaisePropertyChanged("Condition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public object Value2 {
            get {
                return this.value2Field;
            }
            set {
                this.value2Field = value;
                this.RaisePropertyChanged("Value2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int OpenBrackets {
            get {
                return this.openBracketsField;
            }
            set {
                this.openBracketsField = value;
                this.RaisePropertyChanged("OpenBrackets");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int CloseBrackets {
            get {
                return this.closeBracketsField;
            }
            set {
                this.closeBracketsField = value;
                this.RaisePropertyChanged("CloseBrackets");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public FilterOperator Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("Operator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public enum FilterCondition {
        
        /// <remarks/>
        Equals,
        
        /// <remarks/>
        NotEqual,
        
        /// <remarks/>
        Greater,
        
        /// <remarks/>
        GreaterOrEqual,
        
        /// <remarks/>
        Less,
        
        /// <remarks/>
        LessOrEqual,
        
        /// <remarks/>
        Contain,
        
        /// <remarks/>
        StartsWith,
        
        /// <remarks/>
        EndsWith,
        
        /// <remarks/>
        NotContain,
        
        /// <remarks/>
        Between,
        
        /// <remarks/>
        IsNull,
        
        /// <remarks/>
        IsNotNull,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public enum FilterOperator {
        
        /// <remarks/>
        And,
        
        /// <remarks/>
        Or,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Content : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Action[] actionsField;
        
        private Container[] containersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Action[] Actions {
            get {
                return this.actionsField;
            }
            set {
                this.actionsField = value;
                this.RaisePropertyChanged("Actions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Container[] Containers {
            get {
                return this.containersField;
            }
            set {
                this.containersField = value;
                this.RaisePropertyChanged("Containers");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Export", WrapperNamespace="http://www.acumatica.com/untyped/", IsWrapped=true)]
    public partial class ExportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=0)]
        public string screenID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=1)]
        public Velixo.Reports.AcumaticaSoap.Command[] commands;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=2)]
        public Velixo.Reports.AcumaticaSoap.Filter[] filters;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=3)]
        public int topCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=4)]
        public bool includeHeaders;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=5)]
        public bool breakOnError;
        
        public ExportRequest() {
        }
        
        public ExportRequest(string screenID, Velixo.Reports.AcumaticaSoap.Command[] commands, Velixo.Reports.AcumaticaSoap.Filter[] filters, int topCount, bool includeHeaders, bool breakOnError) {
            this.screenID = screenID;
            this.commands = commands;
            this.filters = filters;
            this.topCount = topCount;
            this.includeHeaders = includeHeaders;
            this.breakOnError = breakOnError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportResponse", WrapperNamespace="http://www.acumatica.com/untyped/", IsWrapped=true)]
    public partial class ExportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] ExportResult;
        
        public ExportResponse() {
        }
        
        public ExportResponse(string[][] ExportResult) {
            this.ExportResult = ExportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Import", WrapperNamespace="http://www.acumatica.com/untyped/", IsWrapped=true)]
    public partial class ImportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=0)]
        public string screenID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=1)]
        public Velixo.Reports.AcumaticaSoap.Command[] commands;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=2)]
        public Velixo.Reports.AcumaticaSoap.Filter[] filters;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=4)]
        public bool includedHeaders;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=5)]
        public bool breakOnError;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=6)]
        public bool breakOnIncorrectTarget;
        
        public ImportRequest() {
        }
        
        public ImportRequest(string screenID, Velixo.Reports.AcumaticaSoap.Command[] commands, Velixo.Reports.AcumaticaSoap.Filter[] filters, string[][] data, bool includedHeaders, bool breakOnError, bool breakOnIncorrectTarget) {
            this.screenID = screenID;
            this.commands = commands;
            this.filters = filters;
            this.data = data;
            this.includedHeaders = includedHeaders;
            this.breakOnError = breakOnError;
            this.breakOnIncorrectTarget = breakOnIncorrectTarget;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportResponse", WrapperNamespace="http://www.acumatica.com/untyped/", IsWrapped=true)]
    public partial class ImportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=0)]
        public Velixo.Reports.AcumaticaSoap.ImportResult[] ImportResult;
        
        public ImportResponse() {
        }
        
        public ImportResponse(Velixo.Reports.AcumaticaSoap.ImportResult[] ImportResult) {
            this.ImportResult = ImportResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public enum SchemaMode {
        
        /// <remarks/>
        Basic,
        
        /// <remarks/>
        Detailed,
        
        /// <remarks/>
        DetailedWithHidden,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ScreenSoapChannel : Velixo.Reports.AcumaticaSoap.ScreenSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScreenSoapClient : System.ServiceModel.ClientBase<Velixo.Reports.AcumaticaSoap.ScreenSoap>, Velixo.Reports.AcumaticaSoap.ScreenSoap {
        
        public ScreenSoapClient() {
        }
        
        public ScreenSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScreenSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScreenSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScreenSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Clear(string screenID) {
            base.Channel.Clear(screenID);
        }
        
        public System.Threading.Tasks.Task ClearAsync(string screenID) {
            return base.Channel.ClearAsync(screenID);
        }
        
        public Velixo.Reports.AcumaticaSoap.ProcessResult GetProcessStatus(string screenID) {
            return base.Channel.GetProcessStatus(screenID);
        }
        
        public System.Threading.Tasks.Task<Velixo.Reports.AcumaticaSoap.ProcessResult> GetProcessStatusAsync(string screenID) {
            return base.Channel.GetProcessStatusAsync(screenID);
        }
        
        public Velixo.Reports.AcumaticaSoap.Command[] GetScenario(string scenario) {
            return base.Channel.GetScenario(scenario);
        }
        
        public System.Threading.Tasks.Task<Velixo.Reports.AcumaticaSoap.Command[]> GetScenarioAsync(string scenario) {
            return base.Channel.GetScenarioAsync(scenario);
        }
        
        public Velixo.Reports.AcumaticaSoap.Content GetSchema(string screenID) {
            return base.Channel.GetSchema(screenID);
        }
        
        public System.Threading.Tasks.Task<Velixo.Reports.AcumaticaSoap.Content> GetSchemaAsync(string screenID) {
            return base.Channel.GetSchemaAsync(screenID);
        }
        
        public void SetSchema(string screenID, Velixo.Reports.AcumaticaSoap.Content schema) {
            base.Channel.SetSchema(screenID, schema);
        }
        
        public System.Threading.Tasks.Task SetSchemaAsync(string screenID, Velixo.Reports.AcumaticaSoap.Content schema) {
            return base.Channel.SetSchemaAsync(screenID, schema);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Velixo.Reports.AcumaticaSoap.ExportResponse Velixo.Reports.AcumaticaSoap.ScreenSoap.Export(Velixo.Reports.AcumaticaSoap.ExportRequest request) {
            return base.Channel.Export(request);
        }
        
        public string[][] Export(string screenID, Velixo.Reports.AcumaticaSoap.Command[] commands, Velixo.Reports.AcumaticaSoap.Filter[] filters, int topCount, bool includeHeaders, bool breakOnError) {
            Velixo.Reports.AcumaticaSoap.ExportRequest inValue = new Velixo.Reports.AcumaticaSoap.ExportRequest();
            inValue.screenID = screenID;
            inValue.commands = commands;
            inValue.filters = filters;
            inValue.topCount = topCount;
            inValue.includeHeaders = includeHeaders;
            inValue.breakOnError = breakOnError;
            Velixo.Reports.AcumaticaSoap.ExportResponse retVal = ((Velixo.Reports.AcumaticaSoap.ScreenSoap)(this)).Export(inValue);
            return retVal.ExportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Velixo.Reports.AcumaticaSoap.ExportResponse> Velixo.Reports.AcumaticaSoap.ScreenSoap.ExportAsync(Velixo.Reports.AcumaticaSoap.ExportRequest request) {
            return base.Channel.ExportAsync(request);
        }
        
        public System.Threading.Tasks.Task<Velixo.Reports.AcumaticaSoap.ExportResponse> ExportAsync(string screenID, Velixo.Reports.AcumaticaSoap.Command[] commands, Velixo.Reports.AcumaticaSoap.Filter[] filters, int topCount, bool includeHeaders, bool breakOnError) {
            Velixo.Reports.AcumaticaSoap.ExportRequest inValue = new Velixo.Reports.AcumaticaSoap.ExportRequest();
            inValue.screenID = screenID;
            inValue.commands = commands;
            inValue.filters = filters;
            inValue.topCount = topCount;
            inValue.includeHeaders = includeHeaders;
            inValue.breakOnError = breakOnError;
            return ((Velixo.Reports.AcumaticaSoap.ScreenSoap)(this)).ExportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Velixo.Reports.AcumaticaSoap.ImportResponse Velixo.Reports.AcumaticaSoap.ScreenSoap.Import(Velixo.Reports.AcumaticaSoap.ImportRequest request) {
            return base.Channel.Import(request);
        }
        
        public Velixo.Reports.AcumaticaSoap.ImportResult[] Import(string screenID, Velixo.Reports.AcumaticaSoap.Command[] commands, Velixo.Reports.AcumaticaSoap.Filter[] filters, string[][] data, bool includedHeaders, bool breakOnError, bool breakOnIncorrectTarget) {
            Velixo.Reports.AcumaticaSoap.ImportRequest inValue = new Velixo.Reports.AcumaticaSoap.ImportRequest();
            inValue.screenID = screenID;
            inValue.commands = commands;
            inValue.filters = filters;
            inValue.data = data;
            inValue.includedHeaders = includedHeaders;
            inValue.breakOnError = breakOnError;
            inValue.breakOnIncorrectTarget = breakOnIncorrectTarget;
            Velixo.Reports.AcumaticaSoap.ImportResponse retVal = ((Velixo.Reports.AcumaticaSoap.ScreenSoap)(this)).Import(inValue);
            return retVal.ImportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Velixo.Reports.AcumaticaSoap.ImportResponse> Velixo.Reports.AcumaticaSoap.ScreenSoap.ImportAsync(Velixo.Reports.AcumaticaSoap.ImportRequest request) {
            return base.Channel.ImportAsync(request);
        }
        
        public System.Threading.Tasks.Task<Velixo.Reports.AcumaticaSoap.ImportResponse> ImportAsync(string screenID, Velixo.Reports.AcumaticaSoap.Command[] commands, Velixo.Reports.AcumaticaSoap.Filter[] filters, string[][] data, bool includedHeaders, bool breakOnError, bool breakOnIncorrectTarget) {
            Velixo.Reports.AcumaticaSoap.ImportRequest inValue = new Velixo.Reports.AcumaticaSoap.ImportRequest();
            inValue.screenID = screenID;
            inValue.commands = commands;
            inValue.filters = filters;
            inValue.data = data;
            inValue.includedHeaders = includedHeaders;
            inValue.breakOnError = breakOnError;
            inValue.breakOnIncorrectTarget = breakOnIncorrectTarget;
            return ((Velixo.Reports.AcumaticaSoap.ScreenSoap)(this)).ImportAsync(inValue);
        }
        
        public Velixo.Reports.AcumaticaSoap.Content[] Submit(string screenID, Velixo.Reports.AcumaticaSoap.Command[] commands) {
            return base.Channel.Submit(screenID, commands);
        }
        
        public System.Threading.Tasks.Task<Velixo.Reports.AcumaticaSoap.Content[]> SubmitAsync(string screenID, Velixo.Reports.AcumaticaSoap.Command[] commands) {
            return base.Channel.SubmitAsync(screenID, commands);
        }
        
        public Velixo.Reports.AcumaticaSoap.LoginResult Login(string name, string password) {
            return base.Channel.Login(name, password);
        }
        
        public System.Threading.Tasks.Task<Velixo.Reports.AcumaticaSoap.LoginResult> LoginAsync(string name, string password) {
            return base.Channel.LoginAsync(name, password);
        }
        
        public void Logout() {
            base.Channel.Logout();
        }
        
        public System.Threading.Tasks.Task LogoutAsync() {
            return base.Channel.LogoutAsync();
        }
        
        public void SetBusinessDate(System.DateTime date) {
            base.Channel.SetBusinessDate(date);
        }
        
        public System.Threading.Tasks.Task SetBusinessDateAsync(System.DateTime date) {
            return base.Channel.SetBusinessDateAsync(date);
        }
        
        public void SetLocaleName(string localeName) {
            base.Channel.SetLocaleName(localeName);
        }
        
        public System.Threading.Tasks.Task SetLocaleNameAsync(string localeName) {
            return base.Channel.SetLocaleNameAsync(localeName);
        }
        
        public void SetSchemaMode(Velixo.Reports.AcumaticaSoap.SchemaMode mode) {
            base.Channel.SetSchemaMode(mode);
        }
        
        public System.Threading.Tasks.Task SetSchemaModeAsync(Velixo.Reports.AcumaticaSoap.SchemaMode mode) {
            return base.Channel.SetSchemaModeAsync(mode);
        }
    }
}
